# POST http://localhost:3333/videos
POST https://api-videos2.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o video 01",
    "duration": 180
}

###

# GET http://localhost:3333/videos
# GET http://localhost:3333/videos?search=Video
GET https://api-videos2.onrender.com/videos?search=Video

###

# PUT http://localhost:3333/videos/a75be6d9-9884-4c54-8de1-5bd197acce37
PUT https://api-videos2.onrender.com/videos/054a3da4-3825-421c-a867-ad2f61e6d9af
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o video 03",
    "duration": 210
}

###

# DELETE http://localhost:3333/videos/7b89cef3-5b4b-428c-89dd-6836dd4dbf7b
DELETE https://api-videos2.onrender.com/videos/054a3da4-3825-421c-a867-ad2f61e6d9af
